#TODO compile and test
[source]
git = "https://github.com/maximecb/plush"
shallow_clone = true
[build]
template = "custom"
dependencies = ["sdl2"]
script = """
DYNAMIC_INIT
cookbook_cargo
mkdir -pv "${COOKBOOK_STAGE}/usr/share/plush"
cp -rv "${COOKBOOK_SOURCE}"/examples/* "${COOKBOOK_STAGE}/usr/share/plush"
"""
