#TODO compile and test
[source]
tar = "https://invent.kde.org/utilities/kweather/-/archive/v26.04.3/kweather-v26.04.3.tar.bz2"
shallow_clone = true
[build]
template = "cmake"
cmakeflags = [
    "-DBUILD_PLASMOID=OFF",
    "-DBUILD_KRUNNER=OFF",
]
dev-dependencies = ["host:ecm"]
dependencies = [
    "qt6-base",
    "kconfig6",
    "kirigami6",
    "ki18n6",
    "kcoreaddons6",
    "knotifications6",
    "kweathercore",
    "kirigami-addons",
]
