# limitations: no opengl hardware acceleration, xrandr and text input is hacky
# the meson config don't have xsdl config
#TODO verify if some part of the xserver-xorg patch is needed
#TODO verify if feature flags are correct
#TODO compile and test
# execution script: https://github.com/pelya/xserver-xsdl/blob/xsdl-1.20/start-linux.sh
# linux build with x11 extensions script: https://github.com/pelya/xserver-xsdl/blob/xsdl-1.20/build-xsdl-for-linux.sh
# linux build without x11 extensions script: https://github.com/pelya/xserver-xsdl/blob/xsdl-1.20/build-xsdl-for-linux-no-extensions.sh
[source]
git = "https://github.com/pelya/xserver-xsdl"
rev = "ccd3a7c"
shallow_clone = true
script = """
autotools_recursive_regenerate
"""
[build]
template = "custom"
dependencies = [
    "sdl1",
    "font-util",
    "freetype2",
    "libfontenc",
    "libpng",
    "libpthread-stubs",
    #TODO: used for secure-rpc, needs syslog: "libtirpc",
    "libx11",
    "libxau",
    "libxcb",
    "libxcvt",
    "libxdmcp",
    "libxext",
    "libxfixes",
    "libxfont2",
    "libxkbfile",
    "libxxf86vm",
    "mesa-x11",
    "openssl3",
    "pixman",
    "xkbcomp",
    "x11proto",
    "xtrans",
    "zlib",
]

script = """
env SDL=yes # CFLAGS="-g" # needed?
DYNAMIC_INIT
COOKBOOK_CONFIGURE_FLAGS+=(
    #--prefix="${COOKBOOK_STAGE}/usr" # previous path: `pwd`/data/usr
    #--with-xkb-path=/usr/share/X11/xkb # previous path: `pwd`/data/xkb
    --enable-xsdl
    --enable-kdrive
    --disable-xorg
    --disable-dmx
    --disable-xvfb
    --disable-xnest
    --disable-xquartz
    --disable-xwin
    --disable-xwayland
    --disable-xephyr
    --disable-unit-tests
    --disable-dri
    --disable-dri2
    --disable-dri3
    --disable-glx
    --disable-xf86vidmode
    --disable-config-udev
    --disable-libdrm
    --disable-mitshm
    --disable-composite
    --disable-xres
    --disable-record
    --disable-xv
    --disable-xvmc
    --disable-dga
    --disable-screensaver
    --disable-xdmcp
    --disable-xdm-auth-1
    --disable-present
    --disable-xinerama
    --disable-xf86vidmode
    --disable-xace
    --disable-dbe
    --disable-dpms
    --disable-config-hal
    --disable-clientids
    --disable-linux-acpi
    --disable-linux-apm
    --disable-glamor
    --disable-xshmfence
    --with-systemd-daemon=no
)
cookbook_configure
# ln -sf /usr/bin/xkbcomp data/usr/bin/xkbcomp # needed?
"""
